name: qpsolvers_benchmark
channels:
    - https://conda.anaconda.org/conda-forge
dependencies:
    - cvxopt >= 1.3.0
    - daqp >= 0.5.1
    - ecos >= 2.0.10
    - matplotlib
    - osqp >= 0.6.2
    - pandas
    - pip
    - proxsuite >= 0.3.1
    - qpoases >= 3.2.0
    - qpsolvers >= 3.4.0
    - quadprog >= 0.1.11
    - tabulate
    - pip:
        - highspy >= 1.1.2.dev3
        - py-cpuinfo
        - qpsolvers_benchmark >= 1.0.0
        - scs >= 3.2.2
